spring:
  datasource:
    url: jdbc:mysql://130.193.39.169:33006/goldengroup
    username: root
    password: 402986
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: UTC

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: BOT-SERVICE

server:
  port: 8077

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: WARN

#bot:
#  name: raso_bot
#  token: ${BOT_TOKEN}  # Передача токена через переменные окружения


bot:
  name: raso_bot
  token: 7764343387:AAFVAfign7eUwlZMfMSGmPgRPgR7n6UX7_c

backend:
  api:
    url: http://130.193.39.169:8080/api/
  auth:
    url: http://130.193.39.169:8080/auth/

telegram:
  notification:
    chatIds:
      - 596593025

  bot:
    name: raso_bot
    token: 7764343387:AAFVAfign7eUwlZMfMSGmPgRPgR7n6UX7_c